spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/corn?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
    org.jeecg.modules: DEBUG
  root:
    appender: Console
    path: .