logging:
  level:
    root: DEBUG
  root:
    appender: RollingFile
    path: /home/chenlt/api/
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://192.168.15.26:3306/chenlt_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password: 9ol.(OL>
          driver-class-name: com.mysql.jdbc.Driver
#jeecg专用配置
jeecg :
  path :
    #文件上传根目录 设置
    upload: /home/chenlt/upload
    #webapp文件路径
    webapp: /home/chenlt/webapp
