logging:
  level:
    root: DEBUG
  root:
    appender: RollingFile
    path: /root/app/api/logs

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/corn?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver

#jeecg专用配置
jeecg :
  path :
    #文件上传根目录 设置
    upload: /root/file/upload
    #webapp文件路径
    webapp: /root/file/webapp
