spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/corn?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
#jeecg专用配置
jeecg:
  path:
    #文件上传根目录 设置
    upload: E://corn//upFiles
    public: E://corn
    #文件显示时的前缀
    #pre: /upload/
    pre: http://localhost:89/
    #lucene索引目录
    lucence: E://corn//index
logging:
  root:
    appender: Console
    path: .