corn:
  apiUrl: http://42.192.15.59:89/api
  resourceUrl: http://42.192.15.59/upload/

spring:
  datasource:
    url: jdbc:mysql://42.192.15.59:3306/corn?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: corn
    password: corn2020!@#
    driver-class-name: com.mysql.cj.jdbc.Driver